# Generated by Django 5.2.1 on 2025-06-01 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid in KES', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('OTHER', 'Other')], max_length=20)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, help_text='M-Pesa Checkout Request ID for STK push', max_length=100, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='M-Pesa transaction code (e.g., QBC123XYZ)', max_length=50, null=True, unique=True)),
                ('paypal_transaction_id', models.CharField(blank=True, help_text='Transaction ID from PayPal', max_length=255, null=True, unique=True)),
                ('paypal_order_id', models.CharField(blank=True, help_text='Order ID from PayPal', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sub Counties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or preferences for the swap.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('AWAITING_MATCH', 'Awaiting Match'), ('MATCH_FOUND', 'Match Found - Payment Required'), ('PAYMENT_PENDING', 'Payment Initiated'), ('COMPLETED', 'Completed & Details Revealed'), ('REJECTED', 'Rejected by Admin'), ('CANCELLED_BY_USER', 'Cancelled by User'), ('EXPIRED', 'Expired')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_completed_for_match_reveal', models.BooleanField(default=False)),
                ('match_found_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
