# Generated by Django 5.2.1 on 2025-06-01 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swaps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcounties', to='swaps.county'),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='desired_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desired_swaps', to='swaps.county'),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='desired_subcounty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desired_swaps', to='swaps.subcounty'),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='matched_with_request',
            field=models.OneToOneField(blank=True, help_text='The other swap request this one is matched with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_match_for_request', to='swaps.swaprequest'),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='swap_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='swaps.swaprequest'),
        ),
        migrations.AddField(
            model_name='ward',
            name='subcounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='swaps.subcounty'),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='desired_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desired_swaps', to='swaps.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='subcounty',
            unique_together={('county', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together={('subcounty', 'name')},
        ),
    ]
