# Generated by Django 5.2.1 on 2025-05-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('USER', 'User'), ('AI', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Chat Message',
                'verbose_name_plural': 'AI Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SmartMatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='The input prompt or user profile data sent to the AI for matching.')),
                ('ai_response', models.TextField(help_text='The raw JSON or text response received from the AI.')),
                ('suggestions_data', models.TextField(blank=True, help_text='Parsed smart matching suggestions (e.g., JSON string of schools/requests).', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Smart Match Log',
                'verbose_name_plural': 'Smart Match Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
